/**
 * Generated by Scrooge
 *   version: 4.5.0
 *   rev: 014664de600267b36809bbc85225e26aec286216
 *   built at: 20160203-205352
 */
package com.jxjxgo.account.rpc.domain

import com.twitter.finagle.Thrift
import com.twitter.finagle.stats.{NullStatsReceiver, StatsReceiver}
import com.twitter.scrooge.{ThriftStruct, TReusableMemoryTransport}
import com.twitter.util.{Future, Return, Throw, Throwables}
import java.nio.ByteBuffer
import java.util.Arrays
import org.apache.thrift.protocol._
import org.apache.thrift.TApplicationException
import org.apache.thrift.transport.TMemoryInputTransport
import scala.collection.mutable.{
  ArrayBuffer => mutable$ArrayBuffer, HashMap => mutable$HashMap}
import scala.collection.{Map, Set}

import scala.language.higherKinds


@javax.annotation.Generated(value = Array("com.twitter.scrooge.Compiler"))
class AccountEndpoint$FinagleService(
  iface: AccountEndpoint[Future],
  protocolFactory: TProtocolFactory,
  stats: StatsReceiver,
  maxThriftBufferSize: Int,
  serviceName: String
) extends com.twitter.finagle.Service[Array[Byte], Array[Byte]] {
  import AccountEndpoint._

  def this(
    iface: AccountEndpoint[Future],
    protocolFactory: TProtocolFactory,
    stats: StatsReceiver,
    maxThriftBufferSize: Int
  ) = this(iface, protocolFactory, stats, maxThriftBufferSize, "AccountEndpoint")

  def this(
    iface: AccountEndpoint[Future],
    protocolFactory: TProtocolFactory
  ) = this(iface, protocolFactory, NullStatsReceiver, Thrift.maxThriftBufferSize)

  private[this] val tlReusableBuffer = new ThreadLocal[TReusableMemoryTransport] {
    override def initialValue() = TReusableMemoryTransport(512)
  }

  private[this] def reusableBuffer: TReusableMemoryTransport = {
    val buf = tlReusableBuffer.get()
    buf.reset()
    buf
  }

  private[this] val resetCounter = stats.scope("buffer").counter("resetCount")

  private[this] def resetBuffer(trans: TReusableMemoryTransport): Unit = {
    if (trans.currentCapacity > maxThriftBufferSize) {
      resetCounter.incr()
      tlReusableBuffer.remove()
    }
  }

  protected val functionMap = new mutable$HashMap[String, (TProtocol, Int) => Future[Array[Byte]]]()

  protected def addFunction(name: String, f: (TProtocol, Int) => Future[Array[Byte]]) {
    functionMap(name) = f
  }

  protected def exception(name: String, seqid: Int, code: Int, message: String): Future[Array[Byte]] = {
    try {
      val x = new TApplicationException(code, message)
      val memoryBuffer = reusableBuffer
      try {
        val oprot = protocolFactory.getProtocol(memoryBuffer)

        oprot.writeMessageBegin(new TMessage(name, TMessageType.EXCEPTION, seqid))
        x.write(oprot)
        oprot.writeMessageEnd()
        oprot.getTransport().flush()
        Future.value(Arrays.copyOfRange(memoryBuffer.getArray(), 0, memoryBuffer.length()))
      } finally {
        resetBuffer(memoryBuffer)
      }
    } catch {
      case e: Exception => Future.exception(e)
    }
  }

  protected def reply(name: String, seqid: Int, result: ThriftStruct): Future[Array[Byte]] = {
    try {
      val memoryBuffer = reusableBuffer
      try {
        val oprot = protocolFactory.getProtocol(memoryBuffer)

        oprot.writeMessageBegin(new TMessage(name, TMessageType.REPLY, seqid))
        result.write(oprot)
        oprot.writeMessageEnd()

        Future.value(Arrays.copyOfRange(memoryBuffer.getArray(), 0, memoryBuffer.length()))
      } finally {
        resetBuffer(memoryBuffer)
      }
    } catch {
      case e: Exception => Future.exception(e)
    }
  }

  final def apply(request: Array[Byte]): Future[Array[Byte]] = {
    val inputTransport = new TMemoryInputTransport(request)
    val iprot = protocolFactory.getProtocol(inputTransport)

    try {
      val msg = iprot.readMessageBegin()
      val func = functionMap.get(msg.name)
      func match {
        case _root_.scala.Some(fn) =>
          fn(iprot, msg.seqid)
        case _ =>
          TProtocolUtil.skip(iprot, TType.STRUCT)
          exception(msg.name, msg.seqid, TApplicationException.UNKNOWN_METHOD,
            "Invalid method name: '" + msg.name + "'")
      }
    } catch {
      case e: Exception => Future.exception(e)
    }
  }

  // ---- end boilerplate.

  private[this] val scopedStats = if (serviceName != "") stats.scope(serviceName) else stats
  private[this] object __stats_createAccount {
    val RequestsCounter = scopedStats.scope("createAccount").counter("requests")
    val SuccessCounter = scopedStats.scope("createAccount").counter("success")
    val FailuresCounter = scopedStats.scope("createAccount").counter("failures")
    val FailuresScope = scopedStats.scope("createAccount").scope("failures")
  }
  addFunction("createAccount", { (iprot: TProtocol, seqid: Int) =>
    try {
      __stats_createAccount.RequestsCounter.incr()
      val args = CreateAccount.Args.decode(iprot)
      iprot.readMessageEnd()
      (try {
        iface.createAccount(args.traceId, args.memberId, args.deviceType)
      } catch {
        case e: Exception => Future.exception(e)
      }).flatMap { value: com.jxjxgo.account.rpc.domain.AccountBaseResponse =>
        reply("createAccount", seqid, CreateAccount.Result(success = Some(value)))
      }.rescue {
        case e => Future.exception(e)
      }.respond {
        case Return(_) =>
          __stats_createAccount.SuccessCounter.incr()
        case Throw(ex) =>
          __stats_createAccount.FailuresCounter.incr()
          __stats_createAccount.FailuresScope.counter(Throwables.mkString(ex): _*).incr()
      }
    } catch {
      case e: TProtocolException => {
        iprot.readMessageEnd()
        exception("createAccount", seqid, TApplicationException.PROTOCOL_ERROR, e.getMessage)
      }
      case e: Exception => Future.exception(e)
    }
  })
  private[this] object __stats_getAccount {
    val RequestsCounter = scopedStats.scope("getAccount").counter("requests")
    val SuccessCounter = scopedStats.scope("getAccount").counter("success")
    val FailuresCounter = scopedStats.scope("getAccount").counter("failures")
    val FailuresScope = scopedStats.scope("getAccount").scope("failures")
  }
  addFunction("getAccount", { (iprot: TProtocol, seqid: Int) =>
    try {
      __stats_getAccount.RequestsCounter.incr()
      val args = GetAccount.Args.decode(iprot)
      iprot.readMessageEnd()
      (try {
        iface.getAccount(args.traceId, args.memberId, args.deviceType)
      } catch {
        case e: Exception => Future.exception(e)
      }).flatMap { value: com.jxjxgo.account.rpc.domain.DiamondAccountResponse =>
        reply("getAccount", seqid, GetAccount.Result(success = Some(value)))
      }.rescue {
        case e => Future.exception(e)
      }.respond {
        case Return(_) =>
          __stats_getAccount.SuccessCounter.incr()
        case Throw(ex) =>
          __stats_getAccount.FailuresCounter.incr()
          __stats_getAccount.FailuresScope.counter(Throwables.mkString(ex): _*).incr()
      }
    } catch {
      case e: TProtocolException => {
        iprot.readMessageEnd()
        exception("getAccount", seqid, TApplicationException.PROTOCOL_ERROR, e.getMessage)
      }
      case e: Exception => Future.exception(e)
    }
  })
  private[this] object __stats_getPriceList {
    val RequestsCounter = scopedStats.scope("getPriceList").counter("requests")
    val SuccessCounter = scopedStats.scope("getPriceList").counter("success")
    val FailuresCounter = scopedStats.scope("getPriceList").counter("failures")
    val FailuresScope = scopedStats.scope("getPriceList").scope("failures")
  }
  addFunction("getPriceList", { (iprot: TProtocol, seqid: Int) =>
    try {
      __stats_getPriceList.RequestsCounter.incr()
      val args = GetPriceList.Args.decode(iprot)
      iprot.readMessageEnd()
      (try {
        iface.getPriceList(args.traceId, args.deviceType)
      } catch {
        case e: Exception => Future.exception(e)
      }).flatMap { value: com.jxjxgo.account.rpc.domain.PriceListResponse =>
        reply("getPriceList", seqid, GetPriceList.Result(success = Some(value)))
      }.rescue {
        case e => Future.exception(e)
      }.respond {
        case Return(_) =>
          __stats_getPriceList.SuccessCounter.incr()
        case Throw(ex) =>
          __stats_getPriceList.FailuresCounter.incr()
          __stats_getPriceList.FailuresScope.counter(Throwables.mkString(ex): _*).incr()
      }
    } catch {
      case e: TProtocolException => {
        iprot.readMessageEnd()
        exception("getPriceList", seqid, TApplicationException.PROTOCOL_ERROR, e.getMessage)
      }
      case e: Exception => Future.exception(e)
    }
  })
  private[this] object __stats_getChannelList {
    val RequestsCounter = scopedStats.scope("getChannelList").counter("requests")
    val SuccessCounter = scopedStats.scope("getChannelList").counter("success")
    val FailuresCounter = scopedStats.scope("getChannelList").counter("failures")
    val FailuresScope = scopedStats.scope("getChannelList").scope("failures")
  }
  addFunction("getChannelList", { (iprot: TProtocol, seqid: Int) =>
    try {
      __stats_getChannelList.RequestsCounter.incr()
      val args = GetChannelList.Args.decode(iprot)
      iprot.readMessageEnd()
      (try {
        iface.getChannelList(args.traceId, args.deviceType)
      } catch {
        case e: Exception => Future.exception(e)
      }).flatMap { value: com.jxjxgo.account.rpc.domain.ChannelListResponse =>
        reply("getChannelList", seqid, GetChannelList.Result(success = Some(value)))
      }.rescue {
        case e => Future.exception(e)
      }.respond {
        case Return(_) =>
          __stats_getChannelList.SuccessCounter.incr()
        case Throw(ex) =>
          __stats_getChannelList.FailuresCounter.incr()
          __stats_getChannelList.FailuresScope.counter(Throwables.mkString(ex): _*).incr()
      }
    } catch {
      case e: TProtocolException => {
        iprot.readMessageEnd()
        exception("getChannelList", seqid, TApplicationException.PROTOCOL_ERROR, e.getMessage)
      }
      case e: Exception => Future.exception(e)
    }
  })
  private[this] object __stats_deposit {
    val RequestsCounter = scopedStats.scope("deposit").counter("requests")
    val SuccessCounter = scopedStats.scope("deposit").counter("success")
    val FailuresCounter = scopedStats.scope("deposit").counter("failures")
    val FailuresScope = scopedStats.scope("deposit").scope("failures")
  }
  addFunction("deposit", { (iprot: TProtocol, seqid: Int) =>
    try {
      __stats_deposit.RequestsCounter.incr()
      val args = Deposit.Args.decode(iprot)
      iprot.readMessageEnd()
      (try {
        iface.deposit(args.traceId, args.request)
      } catch {
        case e: Exception => Future.exception(e)
      }).flatMap { value: com.jxjxgo.account.rpc.domain.DepositRequestResponse =>
        reply("deposit", seqid, Deposit.Result(success = Some(value)))
      }.rescue {
        case e => Future.exception(e)
      }.respond {
        case Return(_) =>
          __stats_deposit.SuccessCounter.incr()
        case Throw(ex) =>
          __stats_deposit.FailuresCounter.incr()
          __stats_deposit.FailuresScope.counter(Throwables.mkString(ex): _*).incr()
      }
    } catch {
      case e: TProtocolException => {
        iprot.readMessageEnd()
        exception("deposit", seqid, TApplicationException.PROTOCOL_ERROR, e.getMessage)
      }
      case e: Exception => Future.exception(e)
    }
  })
  private[this] object __stats_queryDepositOrder {
    val RequestsCounter = scopedStats.scope("queryDepositOrder").counter("requests")
    val SuccessCounter = scopedStats.scope("queryDepositOrder").counter("success")
    val FailuresCounter = scopedStats.scope("queryDepositOrder").counter("failures")
    val FailuresScope = scopedStats.scope("queryDepositOrder").scope("failures")
  }
  addFunction("queryDepositOrder", { (iprot: TProtocol, seqid: Int) =>
    try {
      __stats_queryDepositOrder.RequestsCounter.incr()
      val args = QueryDepositOrder.Args.decode(iprot)
      iprot.readMessageEnd()
      (try {
        iface.queryDepositOrder(args.traceId, args.paymentVoucherNo)
      } catch {
        case e: Exception => Future.exception(e)
      }).flatMap { value: com.jxjxgo.account.rpc.domain.DepositResponse =>
        reply("queryDepositOrder", seqid, QueryDepositOrder.Result(success = Some(value)))
      }.rescue {
        case e => Future.exception(e)
      }.respond {
        case Return(_) =>
          __stats_queryDepositOrder.SuccessCounter.incr()
        case Throw(ex) =>
          __stats_queryDepositOrder.FailuresCounter.incr()
          __stats_queryDepositOrder.FailuresScope.counter(Throwables.mkString(ex): _*).incr()
      }
    } catch {
      case e: TProtocolException => {
        iprot.readMessageEnd()
        exception("queryDepositOrder", seqid, TApplicationException.PROTOCOL_ERROR, e.getMessage)
      }
      case e: Exception => Future.exception(e)
    }
  })
  private[this] object __stats_settle {
    val RequestsCounter = scopedStats.scope("settle").counter("requests")
    val SuccessCounter = scopedStats.scope("settle").counter("success")
    val FailuresCounter = scopedStats.scope("settle").counter("failures")
    val FailuresScope = scopedStats.scope("settle").scope("failures")
  }
  addFunction("settle", { (iprot: TProtocol, seqid: Int) =>
    try {
      __stats_settle.RequestsCounter.incr()
      val args = Settle.Args.decode(iprot)
      iprot.readMessageEnd()
      (try {
        iface.settle(args.traceId, args.request)
      } catch {
        case e: Exception => Future.exception(e)
      }).flatMap { value: com.jxjxgo.account.rpc.domain.AccountBaseResponse =>
        reply("settle", seqid, Settle.Result(success = Some(value)))
      }.rescue {
        case e => Future.exception(e)
      }.respond {
        case Return(_) =>
          __stats_settle.SuccessCounter.incr()
        case Throw(ex) =>
          __stats_settle.FailuresCounter.incr()
          __stats_settle.FailuresScope.counter(Throwables.mkString(ex): _*).incr()
      }
    } catch {
      case e: TProtocolException => {
        iprot.readMessageEnd()
        exception("settle", seqid, TApplicationException.PROTOCOL_ERROR, e.getMessage)
      }
      case e: Exception => Future.exception(e)
    }
  })
}