/**
 * Generated by Scrooge
 *   version: 4.5.0
 *   rev: 014664de600267b36809bbc85225e26aec286216
 *   built at: 20160203-205352
 */
package com.jxjxgo.account.rpc.domain

import com.twitter.scrooge.{
  LazyTProtocol,
  TFieldBlob, ThriftException, ThriftStruct, ThriftStructCodec3, ThriftStructFieldInfo,
  ThriftStructMetaData, ThriftUtil}
import org.apache.thrift.protocol._
import org.apache.thrift.transport.{TMemoryBuffer, TTransport}
import java.nio.ByteBuffer
import java.util.Arrays
import scala.collection.immutable.{Map => immutable$Map}
import scala.collection.mutable.Builder
import scala.collection.mutable.{
  ArrayBuffer => mutable$ArrayBuffer, Buffer => mutable$Buffer,
  HashMap => mutable$HashMap, HashSet => mutable$HashSet}
import scala.collection.{Map, Set}


object DepositResponse extends ThriftStructCodec3[DepositResponse] {
  private val NoPassthroughFields = immutable$Map.empty[Short, TFieldBlob]
  val Struct = new TStruct("DepositResponse")
  val CodeField = new TField("code", TType.STRING, 1)
  val CodeFieldManifest = implicitly[Manifest[String]]
  val PaymentVoucherNoField = new TField("paymentVoucherNo", TType.STRING, 2)
  val PaymentVoucherNoFieldManifest = implicitly[Manifest[String]]
  val AccountIdField = new TField("accountId", TType.I64, 3)
  val AccountIdFieldManifest = implicitly[Manifest[Long]]
  val MemberIdField = new TField("memberId", TType.I64, 4)
  val MemberIdFieldManifest = implicitly[Manifest[Long]]
  val TradeTypeField = new TField("tradeType", TType.I32, 5)
  val TradeTypeFieldManifest = implicitly[Manifest[Int]]
  val TradeStatusField = new TField("tradeStatus", TType.I32, 6)
  val TradeStatusFieldManifest = implicitly[Manifest[Int]]
  val DiamondAcountField = new TField("diamondAcount", TType.I32, 7)
  val DiamondAcountFieldManifest = implicitly[Manifest[Int]]
  val AmountField = new TField("amount", TType.STRING, 8)
  val AmountFieldManifest = implicitly[Manifest[String]]
  val GmtCreateField = new TField("gmtCreate", TType.I64, 9)
  val GmtCreateFieldManifest = implicitly[Manifest[Long]]
  val GmtUpdateField = new TField("gmtUpdate", TType.I64, 10)
  val GmtUpdateFieldManifest = implicitly[Manifest[Long]]

  /**
   * Field information in declaration order.
   */
  lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
    new ThriftStructFieldInfo(
      CodeField,
      false,
      false,
      CodeFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    ),
    new ThriftStructFieldInfo(
      PaymentVoucherNoField,
      false,
      false,
      PaymentVoucherNoFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    ),
    new ThriftStructFieldInfo(
      AccountIdField,
      false,
      false,
      AccountIdFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    ),
    new ThriftStructFieldInfo(
      MemberIdField,
      false,
      false,
      MemberIdFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    ),
    new ThriftStructFieldInfo(
      TradeTypeField,
      false,
      false,
      TradeTypeFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    ),
    new ThriftStructFieldInfo(
      TradeStatusField,
      false,
      false,
      TradeStatusFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    ),
    new ThriftStructFieldInfo(
      DiamondAcountField,
      false,
      false,
      DiamondAcountFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    ),
    new ThriftStructFieldInfo(
      AmountField,
      false,
      false,
      AmountFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    ),
    new ThriftStructFieldInfo(
      GmtCreateField,
      false,
      false,
      GmtCreateFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    ),
    new ThriftStructFieldInfo(
      GmtUpdateField,
      false,
      false,
      GmtUpdateFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    )
  )

  lazy val structAnnotations: immutable$Map[String, String] =
    immutable$Map.empty[String, String]

  /**
   * Checks that all required fields are non-null.
   */
  def validate(_item: DepositResponse): Unit = {
  }

  def withoutPassthroughFields(original: DepositResponse): DepositResponse =
    new Immutable(
      code =
        {
          val field = original.code
          field
        },
      paymentVoucherNo =
        {
          val field = original.paymentVoucherNo
          field
        },
      accountId =
        {
          val field = original.accountId
          field
        },
      memberId =
        {
          val field = original.memberId
          field
        },
      tradeType =
        {
          val field = original.tradeType
          field
        },
      tradeStatus =
        {
          val field = original.tradeStatus
          field
        },
      diamondAcount =
        {
          val field = original.diamondAcount
          field
        },
      amount =
        {
          val field = original.amount
          field
        },
      gmtCreate =
        {
          val field = original.gmtCreate
          field
        },
      gmtUpdate =
        {
          val field = original.gmtUpdate
          field
        }
    )

  override def encode(_item: DepositResponse, _oproto: TProtocol): Unit = {
    _item.write(_oproto)
  }

  private[this] def lazyDecode(_iprot: LazyTProtocol): DepositResponse = {

    var codeOffset: Int = -1
    var paymentVoucherNoOffset: Int = -1
    var accountId: Long = 0L
    var memberId: Long = 0L
    var tradeType: Int = 0
    var tradeStatus: Int = 0
    var diamondAcount: Int = 0
    var amountOffset: Int = -1
    var gmtCreate: Long = 0L
    var gmtUpdate: Long = 0L

    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false
    val _start_offset = _iprot.offset

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.STRING =>
                codeOffset = _iprot.offsetSkipString
    
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'code' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.STRING =>
                paymentVoucherNoOffset = _iprot.offsetSkipString
    
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'paymentVoucherNo' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 3 =>
            _field.`type` match {
              case TType.I64 =>
    
                accountId = readAccountIdValue(_iprot)
              case _actualType =>
                val _expectedType = TType.I64
                throw new TProtocolException(
                  "Received wrong type for field 'accountId' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 4 =>
            _field.`type` match {
              case TType.I64 =>
    
                memberId = readMemberIdValue(_iprot)
              case _actualType =>
                val _expectedType = TType.I64
                throw new TProtocolException(
                  "Received wrong type for field 'memberId' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 5 =>
            _field.`type` match {
              case TType.I32 =>
    
                tradeType = readTradeTypeValue(_iprot)
              case _actualType =>
                val _expectedType = TType.I32
                throw new TProtocolException(
                  "Received wrong type for field 'tradeType' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 6 =>
            _field.`type` match {
              case TType.I32 =>
    
                tradeStatus = readTradeStatusValue(_iprot)
              case _actualType =>
                val _expectedType = TType.I32
                throw new TProtocolException(
                  "Received wrong type for field 'tradeStatus' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 7 =>
            _field.`type` match {
              case TType.I32 =>
    
                diamondAcount = readDiamondAcountValue(_iprot)
              case _actualType =>
                val _expectedType = TType.I32
                throw new TProtocolException(
                  "Received wrong type for field 'diamondAcount' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 8 =>
            _field.`type` match {
              case TType.STRING =>
                amountOffset = _iprot.offsetSkipString
    
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'amount' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 9 =>
            _field.`type` match {
              case TType.I64 =>
    
                gmtCreate = readGmtCreateValue(_iprot)
              case _actualType =>
                val _expectedType = TType.I64
                throw new TProtocolException(
                  "Received wrong type for field 'gmtCreate' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 10 =>
            _field.`type` match {
              case TType.I64 =>
    
                gmtUpdate = readGmtUpdateValue(_iprot)
              case _actualType =>
                val _expectedType = TType.I64
                throw new TProtocolException(
                  "Received wrong type for field 'gmtUpdate' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    new LazyImmutable(
      _iprot,
      _iprot.buffer,
      _start_offset,
      _iprot.offset,
      codeOffset,
      paymentVoucherNoOffset,
      accountId,
      memberId,
      tradeType,
      tradeStatus,
      diamondAcount,
      amountOffset,
      gmtCreate,
      gmtUpdate,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  override def decode(_iprot: TProtocol): DepositResponse =
    _iprot match {
      case i: LazyTProtocol => lazyDecode(i)
      case i => eagerDecode(i)
    }

  private[this] def eagerDecode(_iprot: TProtocol): DepositResponse = {
    var code: String = ""
    var paymentVoucherNo: String = ""
    var accountId: Long = 0L
    var memberId: Long = 0L
    var tradeType: Int = 0
    var tradeStatus: Int = 0
    var diamondAcount: Int = 0
    var amount: String = ""
    var gmtCreate: Long = 0L
    var gmtUpdate: Long = 0L
    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.STRING =>
                code = readCodeValue(_iprot)
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'code' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.STRING =>
                paymentVoucherNo = readPaymentVoucherNoValue(_iprot)
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'paymentVoucherNo' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 3 =>
            _field.`type` match {
              case TType.I64 =>
                accountId = readAccountIdValue(_iprot)
              case _actualType =>
                val _expectedType = TType.I64
                throw new TProtocolException(
                  "Received wrong type for field 'accountId' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 4 =>
            _field.`type` match {
              case TType.I64 =>
                memberId = readMemberIdValue(_iprot)
              case _actualType =>
                val _expectedType = TType.I64
                throw new TProtocolException(
                  "Received wrong type for field 'memberId' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 5 =>
            _field.`type` match {
              case TType.I32 =>
                tradeType = readTradeTypeValue(_iprot)
              case _actualType =>
                val _expectedType = TType.I32
                throw new TProtocolException(
                  "Received wrong type for field 'tradeType' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 6 =>
            _field.`type` match {
              case TType.I32 =>
                tradeStatus = readTradeStatusValue(_iprot)
              case _actualType =>
                val _expectedType = TType.I32
                throw new TProtocolException(
                  "Received wrong type for field 'tradeStatus' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 7 =>
            _field.`type` match {
              case TType.I32 =>
                diamondAcount = readDiamondAcountValue(_iprot)
              case _actualType =>
                val _expectedType = TType.I32
                throw new TProtocolException(
                  "Received wrong type for field 'diamondAcount' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 8 =>
            _field.`type` match {
              case TType.STRING =>
                amount = readAmountValue(_iprot)
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'amount' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 9 =>
            _field.`type` match {
              case TType.I64 =>
                gmtCreate = readGmtCreateValue(_iprot)
              case _actualType =>
                val _expectedType = TType.I64
                throw new TProtocolException(
                  "Received wrong type for field 'gmtCreate' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 10 =>
            _field.`type` match {
              case TType.I64 =>
                gmtUpdate = readGmtUpdateValue(_iprot)
              case _actualType =>
                val _expectedType = TType.I64
                throw new TProtocolException(
                  "Received wrong type for field 'gmtUpdate' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    new Immutable(
      code,
      paymentVoucherNo,
      accountId,
      memberId,
      tradeType,
      tradeStatus,
      diamondAcount,
      amount,
      gmtCreate,
      gmtUpdate,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  def apply(
    code: String = "",
    paymentVoucherNo: String = "",
    accountId: Long = 0L,
    memberId: Long = 0L,
    tradeType: Int = 0,
    tradeStatus: Int = 0,
    diamondAcount: Int = 0,
    amount: String = "",
    gmtCreate: Long = 0L,
    gmtUpdate: Long = 0L
  ): DepositResponse =
    new Immutable(
      code,
      paymentVoucherNo,
      accountId,
      memberId,
      tradeType,
      tradeStatus,
      diamondAcount,
      amount,
      gmtCreate,
      gmtUpdate
    )

  def unapply(_item: DepositResponse): _root_.scala.Option[scala.Product10[String, String, Long, Long, Int, Int, Int, String, Long, Long]] = _root_.scala.Some(_item)


  @inline private def readCodeValue(_iprot: TProtocol): String = {
    _iprot.readString()
  }

  @inline private def writeCodeField(code_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(CodeField)
    writeCodeValue(code_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeCodeValue(code_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeString(code_item)
  }

  @inline private def readPaymentVoucherNoValue(_iprot: TProtocol): String = {
    _iprot.readString()
  }

  @inline private def writePaymentVoucherNoField(paymentVoucherNo_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(PaymentVoucherNoField)
    writePaymentVoucherNoValue(paymentVoucherNo_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writePaymentVoucherNoValue(paymentVoucherNo_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeString(paymentVoucherNo_item)
  }

  @inline private def readAccountIdValue(_iprot: TProtocol): Long = {
    _iprot.readI64()
  }

  @inline private def writeAccountIdField(accountId_item: Long, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(AccountIdField)
    writeAccountIdValue(accountId_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeAccountIdValue(accountId_item: Long, _oprot: TProtocol): Unit = {
    _oprot.writeI64(accountId_item)
  }

  @inline private def readMemberIdValue(_iprot: TProtocol): Long = {
    _iprot.readI64()
  }

  @inline private def writeMemberIdField(memberId_item: Long, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(MemberIdField)
    writeMemberIdValue(memberId_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeMemberIdValue(memberId_item: Long, _oprot: TProtocol): Unit = {
    _oprot.writeI64(memberId_item)
  }

  @inline private def readTradeTypeValue(_iprot: TProtocol): Int = {
    _iprot.readI32()
  }

  @inline private def writeTradeTypeField(tradeType_item: Int, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(TradeTypeField)
    writeTradeTypeValue(tradeType_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeTradeTypeValue(tradeType_item: Int, _oprot: TProtocol): Unit = {
    _oprot.writeI32(tradeType_item)
  }

  @inline private def readTradeStatusValue(_iprot: TProtocol): Int = {
    _iprot.readI32()
  }

  @inline private def writeTradeStatusField(tradeStatus_item: Int, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(TradeStatusField)
    writeTradeStatusValue(tradeStatus_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeTradeStatusValue(tradeStatus_item: Int, _oprot: TProtocol): Unit = {
    _oprot.writeI32(tradeStatus_item)
  }

  @inline private def readDiamondAcountValue(_iprot: TProtocol): Int = {
    _iprot.readI32()
  }

  @inline private def writeDiamondAcountField(diamondAcount_item: Int, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(DiamondAcountField)
    writeDiamondAcountValue(diamondAcount_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeDiamondAcountValue(diamondAcount_item: Int, _oprot: TProtocol): Unit = {
    _oprot.writeI32(diamondAcount_item)
  }

  @inline private def readAmountValue(_iprot: TProtocol): String = {
    _iprot.readString()
  }

  @inline private def writeAmountField(amount_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(AmountField)
    writeAmountValue(amount_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeAmountValue(amount_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeString(amount_item)
  }

  @inline private def readGmtCreateValue(_iprot: TProtocol): Long = {
    _iprot.readI64()
  }

  @inline private def writeGmtCreateField(gmtCreate_item: Long, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(GmtCreateField)
    writeGmtCreateValue(gmtCreate_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeGmtCreateValue(gmtCreate_item: Long, _oprot: TProtocol): Unit = {
    _oprot.writeI64(gmtCreate_item)
  }

  @inline private def readGmtUpdateValue(_iprot: TProtocol): Long = {
    _iprot.readI64()
  }

  @inline private def writeGmtUpdateField(gmtUpdate_item: Long, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(GmtUpdateField)
    writeGmtUpdateValue(gmtUpdate_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeGmtUpdateValue(gmtUpdate_item: Long, _oprot: TProtocol): Unit = {
    _oprot.writeI64(gmtUpdate_item)
  }


  object Immutable extends ThriftStructCodec3[DepositResponse] {
    override def encode(_item: DepositResponse, _oproto: TProtocol): Unit = { _item.write(_oproto) }
    override def decode(_iprot: TProtocol): DepositResponse = DepositResponse.decode(_iprot)
    override lazy val metaData: ThriftStructMetaData[DepositResponse] = DepositResponse.metaData
  }

  /**
   * The default read-only implementation of DepositResponse.  You typically should not need to
   * directly reference this class; instead, use the DepositResponse.apply method to construct
   * new instances.
   */
  class Immutable(
      val code: String,
      val paymentVoucherNo: String,
      val accountId: Long,
      val memberId: Long,
      val tradeType: Int,
      val tradeStatus: Int,
      val diamondAcount: Int,
      val amount: String,
      val gmtCreate: Long,
      val gmtUpdate: Long,
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends DepositResponse {
    def this(
      code: String = "",
      paymentVoucherNo: String = "",
      accountId: Long = 0L,
      memberId: Long = 0L,
      tradeType: Int = 0,
      tradeStatus: Int = 0,
      diamondAcount: Int = 0,
      amount: String = "",
      gmtCreate: Long = 0L,
      gmtUpdate: Long = 0L
    ) = this(
      code,
      paymentVoucherNo,
      accountId,
      memberId,
      tradeType,
      tradeStatus,
      diamondAcount,
      amount,
      gmtCreate,
      gmtUpdate,
      Map.empty
    )
  }

  /**
   * This is another Immutable, this however keeps strings as lazy values that are lazily decoded from the backing
   * array byte on read.
   */
  private[this] class LazyImmutable(
      _proto: LazyTProtocol,
      _buf: Array[Byte],
      _start_offset: Int,
      _end_offset: Int,
      codeOffset: Int,
      paymentVoucherNoOffset: Int,
      val accountId: Long,
      val memberId: Long,
      val tradeType: Int,
      val tradeStatus: Int,
      val diamondAcount: Int,
      amountOffset: Int,
      val gmtCreate: Long,
      val gmtUpdate: Long,
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends DepositResponse {

    override def write(_oprot: TProtocol): Unit = {
      _oprot match {
        case i: LazyTProtocol => i.writeRaw(_buf, _start_offset, _end_offset - _start_offset)
        case _ => super.write(_oprot)
      }
    }

    lazy val code: String =
      if (codeOffset == -1)
        ""
      else {
        _proto.decodeString(_buf, codeOffset)
      }
    lazy val paymentVoucherNo: String =
      if (paymentVoucherNoOffset == -1)
        ""
      else {
        _proto.decodeString(_buf, paymentVoucherNoOffset)
      }
    lazy val amount: String =
      if (amountOffset == -1)
        ""
      else {
        _proto.decodeString(_buf, amountOffset)
      }

    /**
     * Override the super hash code to make it a lazy val rather than def.
     *
     * Calculating the hash code can be expensive, caching it where possible
     * can provide significant performance wins. (Key in a hash map for instance)
     * Usually not safe since the normal constructor will accept a mutable map or
     * set as an arg
     * Here however we control how the class is generated from serialized data.
     * With the class private and the contract that we throw away our mutable references
     * having the hash code lazy here is safe.
     */
    override lazy val hashCode = super.hashCode
  }

  /**
   * This Proxy trait allows you to extend the DepositResponse trait with additional state or
   * behavior and implement the read-only methods from DepositResponse using an underlying
   * instance.
   */
  trait Proxy extends DepositResponse {
    protected def _underlying_DepositResponse: DepositResponse
    override def code: String = _underlying_DepositResponse.code
    override def paymentVoucherNo: String = _underlying_DepositResponse.paymentVoucherNo
    override def accountId: Long = _underlying_DepositResponse.accountId
    override def memberId: Long = _underlying_DepositResponse.memberId
    override def tradeType: Int = _underlying_DepositResponse.tradeType
    override def tradeStatus: Int = _underlying_DepositResponse.tradeStatus
    override def diamondAcount: Int = _underlying_DepositResponse.diamondAcount
    override def amount: String = _underlying_DepositResponse.amount
    override def gmtCreate: Long = _underlying_DepositResponse.gmtCreate
    override def gmtUpdate: Long = _underlying_DepositResponse.gmtUpdate
    override def _passthroughFields = _underlying_DepositResponse._passthroughFields
  }
}

trait DepositResponse
  extends ThriftStruct
  with scala.Product10[String, String, Long, Long, Int, Int, Int, String, Long, Long]
  with java.io.Serializable
{
  import DepositResponse._

  def code: String
  def paymentVoucherNo: String
  def accountId: Long
  def memberId: Long
  def tradeType: Int
  def tradeStatus: Int
  def diamondAcount: Int
  def amount: String
  def gmtCreate: Long
  def gmtUpdate: Long

  def _passthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty

  def _1 = code
  def _2 = paymentVoucherNo
  def _3 = accountId
  def _4 = memberId
  def _5 = tradeType
  def _6 = tradeStatus
  def _7 = diamondAcount
  def _8 = amount
  def _9 = gmtCreate
  def _10 = gmtUpdate


  /**
   * Gets a field value encoded as a binary blob using TCompactProtocol.  If the specified field
   * is present in the passthrough map, that value is returned.  Otherwise, if the specified field
   * is known and not optional and set to None, then the field is serialized and returned.
   */
  def getFieldBlob(_fieldId: Short): _root_.scala.Option[TFieldBlob] = {
    lazy val _buff = new TMemoryBuffer(32)
    lazy val _oprot = new TCompactProtocol(_buff)
    _passthroughFields.get(_fieldId) match {
      case blob: _root_.scala.Some[TFieldBlob] => blob
      case _root_.scala.None => {
        val _fieldOpt: _root_.scala.Option[TField] =
          _fieldId match {
            case 1 =>
              if (code ne null) {
                writeCodeValue(code, _oprot)
                _root_.scala.Some(DepositResponse.CodeField)
              } else {
                _root_.scala.None
              }
            case 2 =>
              if (paymentVoucherNo ne null) {
                writePaymentVoucherNoValue(paymentVoucherNo, _oprot)
                _root_.scala.Some(DepositResponse.PaymentVoucherNoField)
              } else {
                _root_.scala.None
              }
            case 3 =>
              if (true) {
                writeAccountIdValue(accountId, _oprot)
                _root_.scala.Some(DepositResponse.AccountIdField)
              } else {
                _root_.scala.None
              }
            case 4 =>
              if (true) {
                writeMemberIdValue(memberId, _oprot)
                _root_.scala.Some(DepositResponse.MemberIdField)
              } else {
                _root_.scala.None
              }
            case 5 =>
              if (true) {
                writeTradeTypeValue(tradeType, _oprot)
                _root_.scala.Some(DepositResponse.TradeTypeField)
              } else {
                _root_.scala.None
              }
            case 6 =>
              if (true) {
                writeTradeStatusValue(tradeStatus, _oprot)
                _root_.scala.Some(DepositResponse.TradeStatusField)
              } else {
                _root_.scala.None
              }
            case 7 =>
              if (true) {
                writeDiamondAcountValue(diamondAcount, _oprot)
                _root_.scala.Some(DepositResponse.DiamondAcountField)
              } else {
                _root_.scala.None
              }
            case 8 =>
              if (amount ne null) {
                writeAmountValue(amount, _oprot)
                _root_.scala.Some(DepositResponse.AmountField)
              } else {
                _root_.scala.None
              }
            case 9 =>
              if (true) {
                writeGmtCreateValue(gmtCreate, _oprot)
                _root_.scala.Some(DepositResponse.GmtCreateField)
              } else {
                _root_.scala.None
              }
            case 10 =>
              if (true) {
                writeGmtUpdateValue(gmtUpdate, _oprot)
                _root_.scala.Some(DepositResponse.GmtUpdateField)
              } else {
                _root_.scala.None
              }
            case _ => _root_.scala.None
          }
        _fieldOpt match {
          case _root_.scala.Some(_field) =>
            val _data = Arrays.copyOfRange(_buff.getArray, 0, _buff.length)
            _root_.scala.Some(TFieldBlob(_field, _data))
          case _root_.scala.None =>
            _root_.scala.None
        }
      }
    }
  }

  /**
   * Collects TCompactProtocol-encoded field values according to `getFieldBlob` into a map.
   */
  def getFieldBlobs(ids: TraversableOnce[Short]): immutable$Map[Short, TFieldBlob] =
    (ids flatMap { id => getFieldBlob(id) map { id -> _ } }).toMap

  /**
   * Sets a field using a TCompactProtocol-encoded binary blob.  If the field is a known
   * field, the blob is decoded and the field is set to the decoded value.  If the field
   * is unknown and passthrough fields are enabled, then the blob will be stored in
   * _passthroughFields.
   */
  def setField(_blob: TFieldBlob): DepositResponse = {
    var code: String = this.code
    var paymentVoucherNo: String = this.paymentVoucherNo
    var accountId: Long = this.accountId
    var memberId: Long = this.memberId
    var tradeType: Int = this.tradeType
    var tradeStatus: Int = this.tradeStatus
    var diamondAcount: Int = this.diamondAcount
    var amount: String = this.amount
    var gmtCreate: Long = this.gmtCreate
    var gmtUpdate: Long = this.gmtUpdate
    var _passthroughFields = this._passthroughFields
    _blob.id match {
      case 1 =>
        code = readCodeValue(_blob.read)
      case 2 =>
        paymentVoucherNo = readPaymentVoucherNoValue(_blob.read)
      case 3 =>
        accountId = readAccountIdValue(_blob.read)
      case 4 =>
        memberId = readMemberIdValue(_blob.read)
      case 5 =>
        tradeType = readTradeTypeValue(_blob.read)
      case 6 =>
        tradeStatus = readTradeStatusValue(_blob.read)
      case 7 =>
        diamondAcount = readDiamondAcountValue(_blob.read)
      case 8 =>
        amount = readAmountValue(_blob.read)
      case 9 =>
        gmtCreate = readGmtCreateValue(_blob.read)
      case 10 =>
        gmtUpdate = readGmtUpdateValue(_blob.read)
      case _ => _passthroughFields += (_blob.id -> _blob)
    }
    new Immutable(
      code,
      paymentVoucherNo,
      accountId,
      memberId,
      tradeType,
      tradeStatus,
      diamondAcount,
      amount,
      gmtCreate,
      gmtUpdate,
      _passthroughFields
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetField(_fieldId: Short): DepositResponse = {
    var code: String = this.code
    var paymentVoucherNo: String = this.paymentVoucherNo
    var accountId: Long = this.accountId
    var memberId: Long = this.memberId
    var tradeType: Int = this.tradeType
    var tradeStatus: Int = this.tradeStatus
    var diamondAcount: Int = this.diamondAcount
    var amount: String = this.amount
    var gmtCreate: Long = this.gmtCreate
    var gmtUpdate: Long = this.gmtUpdate

    _fieldId match {
      case 1 =>
        code = ""
      case 2 =>
        paymentVoucherNo = ""
      case 3 =>
        accountId = 0L
      case 4 =>
        memberId = 0L
      case 5 =>
        tradeType = 0
      case 6 =>
        tradeStatus = 0
      case 7 =>
        diamondAcount = 0
      case 8 =>
        amount = ""
      case 9 =>
        gmtCreate = 0L
      case 10 =>
        gmtUpdate = 0L
      case _ =>
    }
    new Immutable(
      code,
      paymentVoucherNo,
      accountId,
      memberId,
      tradeType,
      tradeStatus,
      diamondAcount,
      amount,
      gmtCreate,
      gmtUpdate,
      _passthroughFields - _fieldId
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetCode: DepositResponse = unsetField(1)

  def unsetPaymentVoucherNo: DepositResponse = unsetField(2)

  def unsetAccountId: DepositResponse = unsetField(3)

  def unsetMemberId: DepositResponse = unsetField(4)

  def unsetTradeType: DepositResponse = unsetField(5)

  def unsetTradeStatus: DepositResponse = unsetField(6)

  def unsetDiamondAcount: DepositResponse = unsetField(7)

  def unsetAmount: DepositResponse = unsetField(8)

  def unsetGmtCreate: DepositResponse = unsetField(9)

  def unsetGmtUpdate: DepositResponse = unsetField(10)


  override def write(_oprot: TProtocol): Unit = {
    DepositResponse.validate(this)
    _oprot.writeStructBegin(Struct)
    if (code ne null) writeCodeField(code, _oprot)
    if (paymentVoucherNo ne null) writePaymentVoucherNoField(paymentVoucherNo, _oprot)
    writeAccountIdField(accountId, _oprot)
    writeMemberIdField(memberId, _oprot)
    writeTradeTypeField(tradeType, _oprot)
    writeTradeStatusField(tradeStatus, _oprot)
    writeDiamondAcountField(diamondAcount, _oprot)
    if (amount ne null) writeAmountField(amount, _oprot)
    writeGmtCreateField(gmtCreate, _oprot)
    writeGmtUpdateField(gmtUpdate, _oprot)
    if (_passthroughFields.nonEmpty) {
      _passthroughFields.values.foreach { _.write(_oprot) }
    }
    _oprot.writeFieldStop()
    _oprot.writeStructEnd()
  }

  def copy(
    code: String = this.code,
    paymentVoucherNo: String = this.paymentVoucherNo,
    accountId: Long = this.accountId,
    memberId: Long = this.memberId,
    tradeType: Int = this.tradeType,
    tradeStatus: Int = this.tradeStatus,
    diamondAcount: Int = this.diamondAcount,
    amount: String = this.amount,
    gmtCreate: Long = this.gmtCreate,
    gmtUpdate: Long = this.gmtUpdate,
    _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
  ): DepositResponse =
    new Immutable(
      code,
      paymentVoucherNo,
      accountId,
      memberId,
      tradeType,
      tradeStatus,
      diamondAcount,
      amount,
      gmtCreate,
      gmtUpdate,
      _passthroughFields
    )

  override def canEqual(other: Any): Boolean = other.isInstanceOf[DepositResponse]

  override def equals(other: Any): Boolean =
    canEqual(other) &&
      _root_.scala.runtime.ScalaRunTime._equals(this, other) &&
      _passthroughFields == other.asInstanceOf[DepositResponse]._passthroughFields

  override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)

  override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)


  override def productArity: Int = 10

  override def productElement(n: Int): Any = n match {
    case 0 => this.code
    case 1 => this.paymentVoucherNo
    case 2 => this.accountId
    case 3 => this.memberId
    case 4 => this.tradeType
    case 5 => this.tradeStatus
    case 6 => this.diamondAcount
    case 7 => this.amount
    case 8 => this.gmtCreate
    case 9 => this.gmtUpdate
    case _ => throw new IndexOutOfBoundsException(n.toString)
  }

  override def productPrefix: String = "DepositResponse"
}