/**
 * Generated by Scrooge
 *   version: 4.5.0
 *   rev: 014664de600267b36809bbc85225e26aec286216
 *   built at: 20160203-205352
 */
package com.jxjxgo.account.rpc.domain

import com.twitter.scrooge.{
  LazyTProtocol,
  TFieldBlob, ThriftException, ThriftStruct, ThriftStructCodec3, ThriftStructFieldInfo,
  ThriftStructMetaData, ThriftUtil}
import org.apache.thrift.protocol._
import org.apache.thrift.transport.{TMemoryBuffer, TTransport}
import java.nio.ByteBuffer
import java.util.Arrays
import scala.collection.immutable.{Map => immutable$Map}
import scala.collection.mutable.Builder
import scala.collection.mutable.{
  ArrayBuffer => mutable$ArrayBuffer, Buffer => mutable$Buffer,
  HashMap => mutable$HashMap, HashSet => mutable$HashSet}
import scala.collection.{Map, Set}


object DiamondPrice extends ThriftStructCodec3[DiamondPrice] {
  private val NoPassthroughFields = immutable$Map.empty[Short, TFieldBlob]
  val Struct = new TStruct("DiamondPrice")
  val CodeField = new TField("code", TType.STRING, 1)
  val CodeFieldManifest = implicitly[Manifest[String]]
  val DiamondAmountField = new TField("diamondAmount", TType.I32, 2)
  val DiamondAmountFieldManifest = implicitly[Manifest[Int]]
  val PriceField = new TField("price", TType.STRING, 3)
  val PriceFieldManifest = implicitly[Manifest[String]]
  val DeviceTypeField = new TField("deviceType", TType.I32, 4)
  val DeviceTypeFieldManifest = implicitly[Manifest[Int]]

  /**
   * Field information in declaration order.
   */
  lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
    new ThriftStructFieldInfo(
      CodeField,
      false,
      false,
      CodeFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    ),
    new ThriftStructFieldInfo(
      DiamondAmountField,
      false,
      false,
      DiamondAmountFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    ),
    new ThriftStructFieldInfo(
      PriceField,
      false,
      false,
      PriceFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    ),
    new ThriftStructFieldInfo(
      DeviceTypeField,
      false,
      false,
      DeviceTypeFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    )
  )

  lazy val structAnnotations: immutable$Map[String, String] =
    immutable$Map.empty[String, String]

  /**
   * Checks that all required fields are non-null.
   */
  def validate(_item: DiamondPrice): Unit = {
  }

  def withoutPassthroughFields(original: DiamondPrice): DiamondPrice =
    new Immutable(
      code =
        {
          val field = original.code
          field
        },
      diamondAmount =
        {
          val field = original.diamondAmount
          field
        },
      price =
        {
          val field = original.price
          field
        },
      deviceType =
        {
          val field = original.deviceType
          field
        }
    )

  override def encode(_item: DiamondPrice, _oproto: TProtocol): Unit = {
    _item.write(_oproto)
  }

  private[this] def lazyDecode(_iprot: LazyTProtocol): DiamondPrice = {

    var codeOffset: Int = -1
    var diamondAmount: Int = 0
    var priceOffset: Int = -1
    var deviceType: Int = 0

    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false
    val _start_offset = _iprot.offset

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.STRING =>
                codeOffset = _iprot.offsetSkipString
    
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'code' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.I32 =>
    
                diamondAmount = readDiamondAmountValue(_iprot)
              case _actualType =>
                val _expectedType = TType.I32
                throw new TProtocolException(
                  "Received wrong type for field 'diamondAmount' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 3 =>
            _field.`type` match {
              case TType.STRING =>
                priceOffset = _iprot.offsetSkipString
    
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'price' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 4 =>
            _field.`type` match {
              case TType.I32 =>
    
                deviceType = readDeviceTypeValue(_iprot)
              case _actualType =>
                val _expectedType = TType.I32
                throw new TProtocolException(
                  "Received wrong type for field 'deviceType' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    new LazyImmutable(
      _iprot,
      _iprot.buffer,
      _start_offset,
      _iprot.offset,
      codeOffset,
      diamondAmount,
      priceOffset,
      deviceType,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  override def decode(_iprot: TProtocol): DiamondPrice =
    _iprot match {
      case i: LazyTProtocol => lazyDecode(i)
      case i => eagerDecode(i)
    }

  private[this] def eagerDecode(_iprot: TProtocol): DiamondPrice = {
    var code: String = ""
    var diamondAmount: Int = 0
    var price: String = ""
    var deviceType: Int = 0
    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.STRING =>
                code = readCodeValue(_iprot)
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'code' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.I32 =>
                diamondAmount = readDiamondAmountValue(_iprot)
              case _actualType =>
                val _expectedType = TType.I32
                throw new TProtocolException(
                  "Received wrong type for field 'diamondAmount' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 3 =>
            _field.`type` match {
              case TType.STRING =>
                price = readPriceValue(_iprot)
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'price' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 4 =>
            _field.`type` match {
              case TType.I32 =>
                deviceType = readDeviceTypeValue(_iprot)
              case _actualType =>
                val _expectedType = TType.I32
                throw new TProtocolException(
                  "Received wrong type for field 'deviceType' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    new Immutable(
      code,
      diamondAmount,
      price,
      deviceType,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  def apply(
    code: String = "",
    diamondAmount: Int = 0,
    price: String = "",
    deviceType: Int = 0
  ): DiamondPrice =
    new Immutable(
      code,
      diamondAmount,
      price,
      deviceType
    )

  def unapply(_item: DiamondPrice): _root_.scala.Option[scala.Product4[String, Int, String, Int]] = _root_.scala.Some(_item)


  @inline private def readCodeValue(_iprot: TProtocol): String = {
    _iprot.readString()
  }

  @inline private def writeCodeField(code_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(CodeField)
    writeCodeValue(code_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeCodeValue(code_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeString(code_item)
  }

  @inline private def readDiamondAmountValue(_iprot: TProtocol): Int = {
    _iprot.readI32()
  }

  @inline private def writeDiamondAmountField(diamondAmount_item: Int, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(DiamondAmountField)
    writeDiamondAmountValue(diamondAmount_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeDiamondAmountValue(diamondAmount_item: Int, _oprot: TProtocol): Unit = {
    _oprot.writeI32(diamondAmount_item)
  }

  @inline private def readPriceValue(_iprot: TProtocol): String = {
    _iprot.readString()
  }

  @inline private def writePriceField(price_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(PriceField)
    writePriceValue(price_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writePriceValue(price_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeString(price_item)
  }

  @inline private def readDeviceTypeValue(_iprot: TProtocol): Int = {
    _iprot.readI32()
  }

  @inline private def writeDeviceTypeField(deviceType_item: Int, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(DeviceTypeField)
    writeDeviceTypeValue(deviceType_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeDeviceTypeValue(deviceType_item: Int, _oprot: TProtocol): Unit = {
    _oprot.writeI32(deviceType_item)
  }


  object Immutable extends ThriftStructCodec3[DiamondPrice] {
    override def encode(_item: DiamondPrice, _oproto: TProtocol): Unit = { _item.write(_oproto) }
    override def decode(_iprot: TProtocol): DiamondPrice = DiamondPrice.decode(_iprot)
    override lazy val metaData: ThriftStructMetaData[DiamondPrice] = DiamondPrice.metaData
  }

  /**
   * The default read-only implementation of DiamondPrice.  You typically should not need to
   * directly reference this class; instead, use the DiamondPrice.apply method to construct
   * new instances.
   */
  class Immutable(
      val code: String,
      val diamondAmount: Int,
      val price: String,
      val deviceType: Int,
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends DiamondPrice {
    def this(
      code: String = "",
      diamondAmount: Int = 0,
      price: String = "",
      deviceType: Int = 0
    ) = this(
      code,
      diamondAmount,
      price,
      deviceType,
      Map.empty
    )
  }

  /**
   * This is another Immutable, this however keeps strings as lazy values that are lazily decoded from the backing
   * array byte on read.
   */
  private[this] class LazyImmutable(
      _proto: LazyTProtocol,
      _buf: Array[Byte],
      _start_offset: Int,
      _end_offset: Int,
      codeOffset: Int,
      val diamondAmount: Int,
      priceOffset: Int,
      val deviceType: Int,
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends DiamondPrice {

    override def write(_oprot: TProtocol): Unit = {
      _oprot match {
        case i: LazyTProtocol => i.writeRaw(_buf, _start_offset, _end_offset - _start_offset)
        case _ => super.write(_oprot)
      }
    }

    lazy val code: String =
      if (codeOffset == -1)
        ""
      else {
        _proto.decodeString(_buf, codeOffset)
      }
    lazy val price: String =
      if (priceOffset == -1)
        ""
      else {
        _proto.decodeString(_buf, priceOffset)
      }

    /**
     * Override the super hash code to make it a lazy val rather than def.
     *
     * Calculating the hash code can be expensive, caching it where possible
     * can provide significant performance wins. (Key in a hash map for instance)
     * Usually not safe since the normal constructor will accept a mutable map or
     * set as an arg
     * Here however we control how the class is generated from serialized data.
     * With the class private and the contract that we throw away our mutable references
     * having the hash code lazy here is safe.
     */
    override lazy val hashCode = super.hashCode
  }

  /**
   * This Proxy trait allows you to extend the DiamondPrice trait with additional state or
   * behavior and implement the read-only methods from DiamondPrice using an underlying
   * instance.
   */
  trait Proxy extends DiamondPrice {
    protected def _underlying_DiamondPrice: DiamondPrice
    override def code: String = _underlying_DiamondPrice.code
    override def diamondAmount: Int = _underlying_DiamondPrice.diamondAmount
    override def price: String = _underlying_DiamondPrice.price
    override def deviceType: Int = _underlying_DiamondPrice.deviceType
    override def _passthroughFields = _underlying_DiamondPrice._passthroughFields
  }
}

trait DiamondPrice
  extends ThriftStruct
  with scala.Product4[String, Int, String, Int]
  with java.io.Serializable
{
  import DiamondPrice._

  def code: String
  def diamondAmount: Int
  def price: String
  def deviceType: Int

  def _passthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty

  def _1 = code
  def _2 = diamondAmount
  def _3 = price
  def _4 = deviceType


  /**
   * Gets a field value encoded as a binary blob using TCompactProtocol.  If the specified field
   * is present in the passthrough map, that value is returned.  Otherwise, if the specified field
   * is known and not optional and set to None, then the field is serialized and returned.
   */
  def getFieldBlob(_fieldId: Short): _root_.scala.Option[TFieldBlob] = {
    lazy val _buff = new TMemoryBuffer(32)
    lazy val _oprot = new TCompactProtocol(_buff)
    _passthroughFields.get(_fieldId) match {
      case blob: _root_.scala.Some[TFieldBlob] => blob
      case _root_.scala.None => {
        val _fieldOpt: _root_.scala.Option[TField] =
          _fieldId match {
            case 1 =>
              if (code ne null) {
                writeCodeValue(code, _oprot)
                _root_.scala.Some(DiamondPrice.CodeField)
              } else {
                _root_.scala.None
              }
            case 2 =>
              if (true) {
                writeDiamondAmountValue(diamondAmount, _oprot)
                _root_.scala.Some(DiamondPrice.DiamondAmountField)
              } else {
                _root_.scala.None
              }
            case 3 =>
              if (price ne null) {
                writePriceValue(price, _oprot)
                _root_.scala.Some(DiamondPrice.PriceField)
              } else {
                _root_.scala.None
              }
            case 4 =>
              if (true) {
                writeDeviceTypeValue(deviceType, _oprot)
                _root_.scala.Some(DiamondPrice.DeviceTypeField)
              } else {
                _root_.scala.None
              }
            case _ => _root_.scala.None
          }
        _fieldOpt match {
          case _root_.scala.Some(_field) =>
            val _data = Arrays.copyOfRange(_buff.getArray, 0, _buff.length)
            _root_.scala.Some(TFieldBlob(_field, _data))
          case _root_.scala.None =>
            _root_.scala.None
        }
      }
    }
  }

  /**
   * Collects TCompactProtocol-encoded field values according to `getFieldBlob` into a map.
   */
  def getFieldBlobs(ids: TraversableOnce[Short]): immutable$Map[Short, TFieldBlob] =
    (ids flatMap { id => getFieldBlob(id) map { id -> _ } }).toMap

  /**
   * Sets a field using a TCompactProtocol-encoded binary blob.  If the field is a known
   * field, the blob is decoded and the field is set to the decoded value.  If the field
   * is unknown and passthrough fields are enabled, then the blob will be stored in
   * _passthroughFields.
   */
  def setField(_blob: TFieldBlob): DiamondPrice = {
    var code: String = this.code
    var diamondAmount: Int = this.diamondAmount
    var price: String = this.price
    var deviceType: Int = this.deviceType
    var _passthroughFields = this._passthroughFields
    _blob.id match {
      case 1 =>
        code = readCodeValue(_blob.read)
      case 2 =>
        diamondAmount = readDiamondAmountValue(_blob.read)
      case 3 =>
        price = readPriceValue(_blob.read)
      case 4 =>
        deviceType = readDeviceTypeValue(_blob.read)
      case _ => _passthroughFields += (_blob.id -> _blob)
    }
    new Immutable(
      code,
      diamondAmount,
      price,
      deviceType,
      _passthroughFields
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetField(_fieldId: Short): DiamondPrice = {
    var code: String = this.code
    var diamondAmount: Int = this.diamondAmount
    var price: String = this.price
    var deviceType: Int = this.deviceType

    _fieldId match {
      case 1 =>
        code = ""
      case 2 =>
        diamondAmount = 0
      case 3 =>
        price = ""
      case 4 =>
        deviceType = 0
      case _ =>
    }
    new Immutable(
      code,
      diamondAmount,
      price,
      deviceType,
      _passthroughFields - _fieldId
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetCode: DiamondPrice = unsetField(1)

  def unsetDiamondAmount: DiamondPrice = unsetField(2)

  def unsetPrice: DiamondPrice = unsetField(3)

  def unsetDeviceType: DiamondPrice = unsetField(4)


  override def write(_oprot: TProtocol): Unit = {
    DiamondPrice.validate(this)
    _oprot.writeStructBegin(Struct)
    if (code ne null) writeCodeField(code, _oprot)
    writeDiamondAmountField(diamondAmount, _oprot)
    if (price ne null) writePriceField(price, _oprot)
    writeDeviceTypeField(deviceType, _oprot)
    if (_passthroughFields.nonEmpty) {
      _passthroughFields.values.foreach { _.write(_oprot) }
    }
    _oprot.writeFieldStop()
    _oprot.writeStructEnd()
  }

  def copy(
    code: String = this.code,
    diamondAmount: Int = this.diamondAmount,
    price: String = this.price,
    deviceType: Int = this.deviceType,
    _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
  ): DiamondPrice =
    new Immutable(
      code,
      diamondAmount,
      price,
      deviceType,
      _passthroughFields
    )

  override def canEqual(other: Any): Boolean = other.isInstanceOf[DiamondPrice]

  override def equals(other: Any): Boolean =
    canEqual(other) &&
      _root_.scala.runtime.ScalaRunTime._equals(this, other) &&
      _passthroughFields == other.asInstanceOf[DiamondPrice]._passthroughFields

  override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)

  override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)


  override def productArity: Int = 4

  override def productElement(n: Int): Any = n match {
    case 0 => this.code
    case 1 => this.diamondAmount
    case 2 => this.price
    case 3 => this.deviceType
    case _ => throw new IndexOutOfBoundsException(n.toString)
  }

  override def productPrefix: String = "DiamondPrice"
}