// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `account.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package RpcAccount;

public interface _AccountEndpointOperationsNC
{
    AccountBaseResponse createAccount(String traceId, long memberId);

    DiamondAccountResponse getAccount(String traceId, long memberId);

    PriceListResponse getPriceList(String traceId);

    ChannelListResponse getChannelList(String traceId);

    DepositRequestResponse deposit(String traceId, DepositRequest request);

    DepositResponse queryDepositOrder(String traceId, String paymentVoucherNo);

    AccountBaseResponse settle(String traceId, SettleRequest request);
}
