// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `account.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package RpcAccount;

public interface _AccountEndpointOperations
{
    AccountBaseResponse createAccount(String traceId, long memberId, Ice.Current __current);

    DiamondAccountResponse getAccount(String traceId, long memberId, Ice.Current __current);

    PriceListResponse getPriceList(String traceId, Ice.Current __current);

    ChannelListResponse getChannelList(String traceId, Ice.Current __current);

    DepositRequestResponse deposit(String traceId, DepositRequest request, Ice.Current __current);

    DepositResponse queryDepositOrder(String traceId, String paymentVoucherNo, Ice.Current __current);

    AccountBaseResponse settle(String traceId, SettleRequest request, Ice.Current __current);
}
