// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `account.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package RpcAccount;

public interface AccountEndpoint extends Ice.Object,
                                         _AccountEndpointOperations, _AccountEndpointOperationsNC
{
    public static final String ice_staticId = "::RpcAccount::AccountEndpoint";

    public static final long serialVersionUID = 6797542112430937535L;
}
