// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `account.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package RpcAccount;

public interface AccountEndpointPrx extends Ice.ObjectPrx
{
    public AccountBaseResponse createAccount(String traceId, long memberId);

    public AccountBaseResponse createAccount(String traceId, long memberId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_createAccount(String traceId, long memberId);

    public Ice.AsyncResult begin_createAccount(String traceId, long memberId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_createAccount(String traceId, long memberId, Ice.Callback __cb);

    public Ice.AsyncResult begin_createAccount(String traceId, long memberId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_createAccount(String traceId, long memberId, Callback_AccountEndpoint_createAccount __cb);

    public Ice.AsyncResult begin_createAccount(String traceId, long memberId, java.util.Map<String, String> __ctx, Callback_AccountEndpoint_createAccount __cb);

    public Ice.AsyncResult begin_createAccount(String traceId,
                                               long memberId,
                                               IceInternal.Functional_GenericCallback1<AccountBaseResponse> __responseCb,
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_createAccount(String traceId,
                                               long memberId,
                                               IceInternal.Functional_GenericCallback1<AccountBaseResponse> __responseCb,
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                               IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_createAccount(String traceId,
                                               long memberId,
                                               java.util.Map<String, String> __ctx,
                                               IceInternal.Functional_GenericCallback1<AccountBaseResponse> __responseCb,
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_createAccount(String traceId,
                                               long memberId,
                                               java.util.Map<String, String> __ctx,
                                               IceInternal.Functional_GenericCallback1<AccountBaseResponse> __responseCb,
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                               IceInternal.Functional_BoolCallback __sentCb);

    public AccountBaseResponse end_createAccount(Ice.AsyncResult __result);

    public DiamondAccountResponse getAccount(String traceId, long memberId);

    public DiamondAccountResponse getAccount(String traceId, long memberId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getAccount(String traceId, long memberId);

    public Ice.AsyncResult begin_getAccount(String traceId, long memberId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getAccount(String traceId, long memberId, Ice.Callback __cb);

    public Ice.AsyncResult begin_getAccount(String traceId, long memberId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getAccount(String traceId, long memberId, Callback_AccountEndpoint_getAccount __cb);

    public Ice.AsyncResult begin_getAccount(String traceId, long memberId, java.util.Map<String, String> __ctx, Callback_AccountEndpoint_getAccount __cb);

    public Ice.AsyncResult begin_getAccount(String traceId,
                                            long memberId,
                                            IceInternal.Functional_GenericCallback1<DiamondAccountResponse> __responseCb,
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getAccount(String traceId,
                                            long memberId,
                                            IceInternal.Functional_GenericCallback1<DiamondAccountResponse> __responseCb,
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                            IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getAccount(String traceId,
                                            long memberId,
                                            java.util.Map<String, String> __ctx,
                                            IceInternal.Functional_GenericCallback1<DiamondAccountResponse> __responseCb,
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getAccount(String traceId,
                                            long memberId,
                                            java.util.Map<String, String> __ctx,
                                            IceInternal.Functional_GenericCallback1<DiamondAccountResponse> __responseCb,
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                            IceInternal.Functional_BoolCallback __sentCb);

    public DiamondAccountResponse end_getAccount(Ice.AsyncResult __result);

    public PriceListResponse getPriceList(String traceId);

    public PriceListResponse getPriceList(String traceId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getPriceList(String traceId);

    public Ice.AsyncResult begin_getPriceList(String traceId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getPriceList(String traceId, Ice.Callback __cb);

    public Ice.AsyncResult begin_getPriceList(String traceId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getPriceList(String traceId, Callback_AccountEndpoint_getPriceList __cb);

    public Ice.AsyncResult begin_getPriceList(String traceId, java.util.Map<String, String> __ctx, Callback_AccountEndpoint_getPriceList __cb);

    public Ice.AsyncResult begin_getPriceList(String traceId,
                                              IceInternal.Functional_GenericCallback1<PriceListResponse> __responseCb,
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getPriceList(String traceId,
                                              IceInternal.Functional_GenericCallback1<PriceListResponse> __responseCb,
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                              IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getPriceList(String traceId,
                                              java.util.Map<String, String> __ctx,
                                              IceInternal.Functional_GenericCallback1<PriceListResponse> __responseCb,
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getPriceList(String traceId,
                                              java.util.Map<String, String> __ctx,
                                              IceInternal.Functional_GenericCallback1<PriceListResponse> __responseCb,
                                              IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                              IceInternal.Functional_BoolCallback __sentCb);

    public PriceListResponse end_getPriceList(Ice.AsyncResult __result);

    public ChannelListResponse getChannelList(String traceId);

    public ChannelListResponse getChannelList(String traceId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getChannelList(String traceId);

    public Ice.AsyncResult begin_getChannelList(String traceId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getChannelList(String traceId, Ice.Callback __cb);

    public Ice.AsyncResult begin_getChannelList(String traceId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getChannelList(String traceId, Callback_AccountEndpoint_getChannelList __cb);

    public Ice.AsyncResult begin_getChannelList(String traceId, java.util.Map<String, String> __ctx, Callback_AccountEndpoint_getChannelList __cb);

    public Ice.AsyncResult begin_getChannelList(String traceId,
                                                IceInternal.Functional_GenericCallback1<ChannelListResponse> __responseCb,
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getChannelList(String traceId,
                                                IceInternal.Functional_GenericCallback1<ChannelListResponse> __responseCb,
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                                IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getChannelList(String traceId,
                                                java.util.Map<String, String> __ctx,
                                                IceInternal.Functional_GenericCallback1<ChannelListResponse> __responseCb,
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getChannelList(String traceId,
                                                java.util.Map<String, String> __ctx,
                                                IceInternal.Functional_GenericCallback1<ChannelListResponse> __responseCb,
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                                IceInternal.Functional_BoolCallback __sentCb);

    public ChannelListResponse end_getChannelList(Ice.AsyncResult __result);

    public DepositRequestResponse deposit(String traceId, DepositRequest request);

    public DepositRequestResponse deposit(String traceId, DepositRequest request, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_deposit(String traceId, DepositRequest request);

    public Ice.AsyncResult begin_deposit(String traceId, DepositRequest request, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_deposit(String traceId, DepositRequest request, Ice.Callback __cb);

    public Ice.AsyncResult begin_deposit(String traceId, DepositRequest request, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_deposit(String traceId, DepositRequest request, Callback_AccountEndpoint_deposit __cb);

    public Ice.AsyncResult begin_deposit(String traceId, DepositRequest request, java.util.Map<String, String> __ctx, Callback_AccountEndpoint_deposit __cb);

    public Ice.AsyncResult begin_deposit(String traceId,
                                         DepositRequest request,
                                         IceInternal.Functional_GenericCallback1<DepositRequestResponse> __responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_deposit(String traceId,
                                         DepositRequest request,
                                         IceInternal.Functional_GenericCallback1<DepositRequestResponse> __responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                         IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_deposit(String traceId,
                                         DepositRequest request,
                                         java.util.Map<String, String> __ctx,
                                         IceInternal.Functional_GenericCallback1<DepositRequestResponse> __responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_deposit(String traceId,
                                         DepositRequest request,
                                         java.util.Map<String, String> __ctx,
                                         IceInternal.Functional_GenericCallback1<DepositRequestResponse> __responseCb,
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                         IceInternal.Functional_BoolCallback __sentCb);

    public DepositRequestResponse end_deposit(Ice.AsyncResult __result);

    public DepositResponse queryDepositOrder(String traceId, String paymentVoucherNo);

    public DepositResponse queryDepositOrder(String traceId, String paymentVoucherNo, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_queryDepositOrder(String traceId, String paymentVoucherNo);

    public Ice.AsyncResult begin_queryDepositOrder(String traceId, String paymentVoucherNo, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_queryDepositOrder(String traceId, String paymentVoucherNo, Ice.Callback __cb);

    public Ice.AsyncResult begin_queryDepositOrder(String traceId, String paymentVoucherNo, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_queryDepositOrder(String traceId, String paymentVoucherNo, Callback_AccountEndpoint_queryDepositOrder __cb);

    public Ice.AsyncResult begin_queryDepositOrder(String traceId, String paymentVoucherNo, java.util.Map<String, String> __ctx, Callback_AccountEndpoint_queryDepositOrder __cb);

    public Ice.AsyncResult begin_queryDepositOrder(String traceId,
                                                   String paymentVoucherNo,
                                                   IceInternal.Functional_GenericCallback1<DepositResponse> __responseCb,
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_queryDepositOrder(String traceId,
                                                   String paymentVoucherNo,
                                                   IceInternal.Functional_GenericCallback1<DepositResponse> __responseCb,
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                                   IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_queryDepositOrder(String traceId,
                                                   String paymentVoucherNo,
                                                   java.util.Map<String, String> __ctx,
                                                   IceInternal.Functional_GenericCallback1<DepositResponse> __responseCb,
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_queryDepositOrder(String traceId,
                                                   String paymentVoucherNo,
                                                   java.util.Map<String, String> __ctx,
                                                   IceInternal.Functional_GenericCallback1<DepositResponse> __responseCb,
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                                   IceInternal.Functional_BoolCallback __sentCb);

    public DepositResponse end_queryDepositOrder(Ice.AsyncResult __result);

    public AccountBaseResponse settle(String traceId, SettleRequest request);

    public AccountBaseResponse settle(String traceId, SettleRequest request, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_settle(String traceId, SettleRequest request);

    public Ice.AsyncResult begin_settle(String traceId, SettleRequest request, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_settle(String traceId, SettleRequest request, Ice.Callback __cb);

    public Ice.AsyncResult begin_settle(String traceId, SettleRequest request, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_settle(String traceId, SettleRequest request, Callback_AccountEndpoint_settle __cb);

    public Ice.AsyncResult begin_settle(String traceId, SettleRequest request, java.util.Map<String, String> __ctx, Callback_AccountEndpoint_settle __cb);

    public Ice.AsyncResult begin_settle(String traceId,
                                        SettleRequest request,
                                        IceInternal.Functional_GenericCallback1<AccountBaseResponse> __responseCb,
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_settle(String traceId,
                                        SettleRequest request,
                                        IceInternal.Functional_GenericCallback1<AccountBaseResponse> __responseCb,
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                        IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_settle(String traceId,
                                        SettleRequest request,
                                        java.util.Map<String, String> __ctx,
                                        IceInternal.Functional_GenericCallback1<AccountBaseResponse> __responseCb,
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_settle(String traceId,
                                        SettleRequest request,
                                        java.util.Map<String, String> __ctx,
                                        IceInternal.Functional_GenericCallback1<AccountBaseResponse> __responseCb,
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                        IceInternal.Functional_BoolCallback __sentCb);

    public AccountBaseResponse end_settle(Ice.AsyncResult __result);
}
